### ISSUE TITLE
1.16.5: how to disable autospy for a single channel

### ISSUE THREAD

**Issue by donvdp** [kangarko/ChatControl#1205]
**reading done**

Hi there, i am using discord for a link to my ingame adminchannel and the discord admin channel. This all works great ! kudo's on the flawless functionality and easy setup!

My question is if I can turn off 'spy' for the 'admin' channel. Here is why:

When i send a message from discord to the minecraft ingame admin channel the message gets received and printed out in the ingame chat. But another copy of that message gets printed as a 'spy' message.

Here is what I see:

![image](https://user-images.githubusercontent.com/10013800/128421766-91bb5b07-861f-404a-bbca-38c9892e0f13.png)

I have read on the wiki that i can do '/spy menu' and disable the spy for that channel, but all my staff sees this too. Is there a way to configurate the channel 'admin' to not have a spy hook ?

Minecraft Version: 1.16.5#783
MySQL: true
BungeeCord: true

**Comment by ElBananaa** [comment]
> **reading done**
> 
> Hi there, i am using discord for a link to my ingame adminchannel and the discord admin channel. This all works great ! kudo's on the flawless functionality and easy setup!
> 
> My question is if I can turn off 'spy' for the 'admin' channel. Here is why:
> 
> When i send a message from discord to the minecraft ingame admin channel the message gets received and printed out in the ingame chat. But another copy of that message gets printed as a 'spy' message.
> 
> Here is what I see:
> 
> ![image](https://user-images.githubusercontent.com/10013800/128421766-91bb5b07-861f-404a-bbca-38c9892e0f13.png)
> 
> I have read on the wiki that i can do '/spy menu' and disable the spy for that channel, but all my staff sees this too. Is there a way to configurate the channel 'admin' to not have a spy hook ?
> 
> Minecraft Version: 1.16.5#783
> MySQL: true
> BungeeCord: true

Hey!
You should be able to turn off spying for a specific channel by setting `Format_Spy` to `none` in your settings file under `Channels.List`
Here's an example with my config file : 
```yaml
  List:
    general:
      Format: general-chat
      Format_Spy: none
    staffchat:
      Format: staff-chat
      Format_Spy: none
      Format_Console: '&7『&c&lSTAFFCHAT&7』{player_prefix} &r{player} &8&l» &r{message}'
```

**Comment by donvdp** [comment]
ive just tried that and was unable to turn spy off for that channel :(

here is what i have got

on the left = my lobby server with the lobby config
on the richt = my prison server with the prison config
on the top the discord

[edit: also: how to remove the [Bungee/<-servername->] prefix?]

![image](https://user-images.githubusercontent.com/10013800/128573554-4be79695-433b-402f-b4e7-1917d9858b1c.png)

**Comment by ElBananaa** [comment]
> ive just tried that and was unable to turn spy off for that channel :(
> 
> here is what i have got
> 
> on the left = my lobby server with the lobby config
> on the richt = my prison server with the prison config
> on the top the discord
> 
> [edit: also: how to remove the [Bungee/<-servername->] prefix?]
> 
> ![image](https://user-images.githubusercontent.com/10013800/128573554-4be79695-433b-402f-b4e7-1917d9858b1c.png)

- Alright, I don't know why the messages are still sent, while, I guess, they shouldn't. I'd suggest waiting for @kangarko to have a look at this issue.

- You can remove the `[Bungee/Servername]` prefix in the settings file, under `Integration.BungeeCord.Prefix` (near the bottom of the file)

EDIT: Looks like it's related to #1180

**Comment by donvdp** [comment]
i found the bungee<servername> config in the settings.yml file

[edit] ohh crap your quick :P Do you even sleep ElBananaa ? haha

**Comment by donvdp** [comment]
When sending an admin chat message from the lobby server to the prison server there do seem to be a few more packages that are being send (having debug: 'bungee' enabled

![image](https://user-images.githubusercontent.com/10013800/128578740-5d7ed9bb-8467-473d-b9b7-76da5ba69b0e.png)

**Comment by ElBananaa** [comment]
> i found the bungee config in the settings.yml file
> 
> [edit] ohh crap your quick :P Do you even sleep ElBananaa ? haha

Haha, yes, it sometimes happens ^^



> When sending an admin chat message from the lobby server to the prison server there do seem to be a few more packages that are being send (having debug: 'bungee' enabled
> 
> ![image](https://user-images.githubusercontent.com/10013800/128578740-5d7ed9bb-8467-473d-b9b7-76da5ba69b0e.png)

Yes this is normal, a few more packets are provided, such as a packet for the tab completion feature, as example.

**Comment by donvdp** [comment]
My debug files (just in case kangarko asks)

https://ufile.io/f/x23uu

**Comment by donvdp** [comment]
bump ?

**Comment by ElBananaa** [comment]
Hey!
Sorry for the delay, it takes a bit longer than expected.
I sent Kangarko a direct message regarding your issue, he will probably have a look at it within a few days ^^

**Comment by kangarko** [comment]
I am going to have a look asap, that'll be in 24h or less :)

**Comment by kangarko** [comment]
Okay from my testing I found and fixed the following problem:

Player A and B are both in admin channels, where player A is on a different server and player B is spying that channel. Then when player A types a message, player B sees the spy message and the chat message, duplication occurs.

This should be resolved in the next version. If that does not fix Discord issue, let me know more steps to reproducing:

> When i send a message from discord to the minecraft ingame admin channel the message gets received and printed out in the ingame chat. But another copy of that message gets printed as a 'spy' message.

When you send a message that gets duplicated, is your account connected in the game? On the same server where it gets duplicated?

**Comment by donvdp** [comment]
> When you send a message that gets duplicated, is your account connected in the game? On the same server where it gets duplicated

yes i was connected ingame when it happend. Testing it while offline i still seem to be having the issue. as shown by the screenshot below..

ill be awaiting the next release :-)  thanks for your quick work !

![image](https://user-images.githubusercontent.com/10013800/129081628-c2b14ce5-4337-49d4-aca9-ac0fd7953901.png)

**Comment by donvdp** [comment]
I have updated to your release from Yesterday @kangarko.

This fixes the ingame seeing of the spy, but the double messages in disord still persists.

Could it possible be like the picture below? Where from discord i send a message (via the DiscordSRV plugin) to the multiple servers that i have, and that sometimes a message gets returned via chatcontrol to the discord server?

![image](https://user-images.githubusercontent.com/10013800/129176770-6b5e9905-3592-41da-a177-8da13a5b9d9e.png)

![image](https://user-images.githubusercontent.com/10013800/129177108-87e4e389-0021-44fe-8a93-330351353d86.png)

**Comment by kangarko** [comment]
So sorry for the delay, I just got busy with recording a training program and my family came to visit.

I was of the same opinion but after having reviewed your code, we do not broadcast to bungee/discord if it already comes from discord :

![a](https://i.imgur.com/qtu150p.png)

In the next version I made messages from discord go broadcasted to bungeecord if that option is enabled. But they are not supposed to get broadcasted back to DiscordSRV.

How is your setup? Do you have DiscordSRV plugin installed for multiple servers?

**Comment by donvdp** [comment]
Discord SRV is setup on every game server i have.
So yes, Survival, Skyblock, prison, the lobby etc.. yes every server runs discordSRV. This is to my knowledge the way to do you according to the DiscordSRV setup wiki.

#1229

**Comment by donvdp** [comment]
![image](https://user-images.githubusercontent.com/10013800/130233208-f20d49e0-75bc-4bd5-aaa4-be184b476f0e.png)

**Comment by kangarko** [comment]
Okay what I would suggest is removing DiscordSRV from every Spigot server and only keeping it on one server. Then using the latest ChatControl, and setting the Forward_From_Bungee key in settings.yml to true on one server.

This server will then forward messages from other bungee servers to Discord if these servers have Discord enabled for their channels. It will also redistribute Discord messages to your BungeeCord network.

These changes are only effective as of yesterday's update.

**Comment by donvdp** [comment]
i have tried this, but the update from yesterday ended in my server booting up with a fatal error for chatcontrol. i had to revert back to 10.5.4 in order to get chat to work ingame. so ill wat until a new release. #1262

**Comment by kangarko** [comment]
Let me know after today's build!

**Comment by kangarko** [comment]
There is also a new Discord integration steps, you can just see our Wiki on GitHub (it is actually simpler now). Closing in good faith todays release patches this bug, let me know below if you need anything else!

**Comment by donvdp** [comment]
Hi there Kangarko, thanks for your development work so far mate :)

unfortunataly i sometimes still get a duplicated message. Yet again, only in discord. The ingame chat never receives a duplicated message. however i now only seem to be able to send messaged to discord when i am on my lobby server.
![image](https://user-images.githubusercontent.com/10013800/130353228-0a61a31f-e8c3-4fd1-8d05-a58000631d88.png)


![image](https://user-images.githubusercontent.com/10013800/130352651-9ae99494-0d1b-44d2-aa9a-0660a3784808.png)



So here is what i did after upgrading bungee and my server with version 10.5.6.

One of my lobby servers I designated as the discordSRV server. and I removed DiscordSRV from ALL other servers.

Here is my setup after reading your wiki.

![image](https://user-images.githubusercontent.com/10013800/130352677-d29c4fbc-a946-418d-abdf-9a790fbad951.png)
![image](https://user-images.githubusercontent.com/10013800/130352680-3094b929-c19e-4e54-adb3-26c579e5d5c5.png)

**Comment by donvdp** [comment]
perhaps i understood wrong but i executed step 5 from the wiki for only the server that i have DiscordSRV on.

![image](https://user-images.githubusercontent.com/10013800/130353374-0c0bf2ae-b091-451a-9e47-c7aa1978c01a.png)

Ill test if adding this step to other servers changes the behaviour

[EDIT]
So ok that worked. Please change the wiki:

![image](https://user-images.githubusercontent.com/10013800/130353438-2b78e022-c2e0-49a0-9118-d649fdebb2ff.png)

Finally, open ChatControl's settings.yml, go to Channels.List section and paste the channel's ID to the Discord_Channel_Id key for channels you want connected. _**Do this for ALL your servers that you want to link to the discord channel.**_

only problem remaining is the duplicated message that i still get.

**Comment by donvdp** [comment]
I would like to add to my previous post:

Since DiscordSRV is only running on 1 server right now (the lobby in my example) messages do **not** get send from discord to minecraft or the other way arround when there is no player on that server. 

Ofcourse you could say: just put discordSRV on a server that always has players, but i dont always have that. Especially when hosting an event on a seperate server.

The {server} node that i use for adminchat now always says "Lobby" whenever there is a message send from discord to minecraft chat. This ofcourse because the message from discord reaches ingame chat via the lobby server.

Perhaps this feature would be beter to be put on the bungeecord server. since that is a centralized node?

**Comment by ElBananaa** [comment]
Hi,
I believe the fact that the message isn't send to an empty server is an intended behavior of the plugin.
I know that messages such as announcements act the same.

I guess the `{server}` variable issue is probably something Kangarko forgot to change ^^

I don't think DiscordSRV supports a bungee setup. (When I say bungee setup, I mean only installing the plugin on the proxy, instead of installing it on a spigot server). So supporting this feature in chatcontrol seems to be kinda problematic when the plugin required doesn't support this itself
I may be wrong tho ^^

Anyways, since the issue persists, I'll reopen your issue. Let's wait for @kangarko now

**Comment by kangarko** [comment]
Thanks for sharing, I have edited our wiki!

Unfortunately as it looks like I am unable to move forward with the problem of empty servers not sending data, this is due to how plugin messaging works in Bukkit, it will simply use at least one online player to send the plugin message to BungeeCord and distribute it to other servers to.

We could of course use an external solution like MySQL however I don't have time for this right now. Alternativelly you can disable our Discord integration all together and either use Essentials Discord addon or look if DiscordSRV also has this issue.

I am here to help you with the others things I can, or correct me if I am wrong and I missed something!

**Comment by donvdp** [comment]
Thanks for the reply, just to clarify:

are you only unable to move forward on the problem of the discord integration not working when the server is empty? 

or 

are you also not able to move forward on the problem with the duplicated messages appearing in discord ?

**Comment by kangarko** [comment]
Hey, sorry for the delay. I am unable to fix "plugin messages not sending to BungeeCord" when the server is empty, which affects Discord at the moment.

However if you set the "Forward_From_Bungee" option to false and install DiscordSRV on each server, I do believe duplication should not happen, please verify with the new version coming up tonight.

**Comment by Squeej** [comment]
I have this issue as well. I was thinking if it's possible to get the bot to delete and resend our messages, maybe we could get the bot and chatcontrol to delete duplicate discord messages? Sure maybe not everyone would want this feature but it could just be something that's added to the settings.yml for servers that struggle with duplicate discord messages

I'm not well versed in how this all works so forgive me if it's impossible or simply too complicated, but if it can be done I think it would be a nifty solution for alot of us

p.s setting forward from bungee to false sadly didn't do the trick

**Comment by kangarko** [comment]
I cannot fix the issue when you have multiple DiscordSRVs installed (or a Discord bungee plugin) over multiple servers and they all fire messages to a single Discord channel, in that case they'll always duplicate. Instead of using a deduplicator, which is unnecessarily complicated, I propose having 1 DiscordSRV installed on 1 Spigot server and using our Forward option.
