### ISSUE TITLE
1.18.2: Cache loading resulting in main thread being halted

### ISSUE THREAD

**Issue by BlueFyreMatt** [kangarko/ChatControl#1888]
@james090500

Minecraft Version: 1.18.2
MySQL: true

Updated to latest ChatControl (10.11.1) and VelocityControl (3.10.0) last night, its resulted in the servers crashing at least once per hour with no specific pattern. The cause of the crash seems to be players logging in and CHC loading the cache for that player, the strange thing is it doesn't happen with every player AKA you can have any number of players connected fine and then the next player will result in a server crash. 

I've attached a pastebin of one the servers logs, I have around 40 others if you'd like them... https://pastebin.com/8GMSKYfj

**Comment by kangarko** [comment]
Sorry to hear this, could you please send me your /chatcontrol debug and if possible, your ChatControl table exported ? You can do this easily in phpmyadmin. I need to reproduce on my end first.

Try setting Clear_Cache_On_Disconnect to true in settings.yml

**Comment by UserDerezzed** [comment]
[Debug](https://ufile.io/l52cbja8)

**Comment by UserDerezzed** [comment]
Is it safe to downgrade?

**Comment by kangarko** [comment]
I don't think downgrading will help, I have identified an issue with database connections not being (properly) closed which was my fault, and I have patched this. A new release will be coming out in 24h.

**Comment by UserDerezzed** [comment]
We still appear to be having the same issue, even after upgrading to the newest version released.

**Comment by kangarko** [comment]
@relavis can you please repost the crash report?

**Comment by UserDerezzed** [comment]
[Crash report](https://www.toptal.com/developers/hastebin/oweqayevew.yaml)

**Comment by kangarko** [comment]
[ChatControl-Red-10.11.4.zip](https://github.com/kangarko/ChatControl-Red/files/8757515/ChatControl-Red-10.11.4.zip)
I have removed a synchronize block from database since I believe it was redundant there and could lead to this lock condition, is this still happening?

**Comment by kangarko** [comment]
(Fyi just use the above JAR that I have uploaded, the next official release may take up to few more days)

**Comment by UserDerezzed** [comment]
This seems to have solved the crashing, however users are now getting "Database busy" messages when trying to chat after the server has been online for a while. Only solved by a restart.

**Comment by BlueFyreMatt** [comment]
To expand on the above^^ When restarting, this error is printed (spammed) during shutdown https://pastebin.com/wfJ2BQAc 

Full error during shutdown: https://pastebin.com/rnBSH3ZT

**Comment by kangarko** [comment]
I have rewritten how we save logs to the database to make the saving mechanism support bulk, meaning if there is multiple logs we no longer open multiple connections, which should prevent this.

I have tested this and could not reproduce any of these issues, but I will keep a close look in case something pops out. Then just please let me know and I am happy to help!

**Comment by UserDerezzed** [comment]
We've just updated the network to 10.11.5 as of 00:30 PST - will update in approximately 10 hours to see if any issues have occurred. Thanks for the bugfixes kangarko!

**Comment by BlueFyreMatt** [comment]
Hi, Unfortunately we're still having issues, here's a copy of the full error and the "Keep calm and DO NOT SHUTDOWN YOUR SERVER" messages.

https://pastebin.com/JMf1xwrK

**Comment by ElBananaa** [comment]
> We've just updated the network to 10.11.5 as of 00:30 PST - will update in approximately 10 hours to see if any issues have occurred. Thanks for the bugfixes kangarko!

10.11.5 isn't out yet so I don't really know how you managed to update to it xD

**Comment by ElBananaa** [comment]
> Hi, Unfortunately we're still having issues, here's a copy of the full error and the "Keep calm and DO NOT SHUTDOWN YOUR SERVER" messages.
> 
> https://pastebin.com/JMf1xwrK

Please wait for the new update to come out. It should include these fixes. (There's no eta)

**Comment by UserDerezzed** [comment]
> > We've just updated the network to 10.11.5 as of 00:30 PST - will update in approximately 10 hours to see if any issues have occurred. Thanks for the bugfixes kangarko!
> 
> 10.11.5 isn't out yet so I don't really know how you managed to update to it xD

I compiled from source

**Comment by kangarko** [comment]
Thanks, I will release the next version tomorrow.

**Comment by UserDerezzed** [comment]
Seems to have still not been fixed on 10.11.6. 
[Crash log](https://www.toptal.com/developers/hastebin/sawimayuxo)

**Comment by kangarko** [comment]
I have removed some synchronization which may have lead to these dead locks. I apologize. Try this version: https://ufile.io/bnxqhsj8

The problem is that I am already traveling and will be back home after June 21st. @ElBananaa may assist you until then.

**Comment by x1p** [comment]
FYI: I'm still getting the `Database batch update is still processing` messages with this experimental build.

**Comment by ElBananaa** [comment]
> Reference in ne

Did you try to clean your log table to see if that helps?
Also, are you using mails?

**Comment by x1p** [comment]
If you're refering to me: no I did not clear any table. That would defeat the whole purpose of a log function, wouldn't it?

No I'm not using mails, nor pm's nor channels. I have only chat, signs, books and anvils. I used to have commands too, but following advice from above, I skipped the commands to reduce the amount of data and turned on the `Clear_Cache_On_Disconnect` function.
The amount of logged things is really not that much. It gives these messages too when there is hardly any activity online. The database should have no trouble at all handling that few data.

**Comment by ElBananaa** [comment]
> If you're refering to me: no I did not clear any table. That would defeat the whole purpose of a log function, wouldn't it?
> 
> No I'm not using mails, nor pm's nor channels. I have only chat, signs, books and anvils. I used to have commands too, but following advice from above, I skipped the commands to reduce the amount of data and turned on the `Clear_Cache_On_Disconnect` function. The amount of logged things is really not that much. It gives these messages too when there is hardly any activity online. The database should have no trouble at all handling that few data.

Yeah, that's pretty weird, I personally never experienced a such issue even with a high player activity.
Is there any chance your database host provider has a rate limit on db requests? This is the only thing that comes to my mind right now.

**Comment by ElBananaa** [comment]
Hey, getting back on this. Anyone here's got any news about this? Does the issue persists? I'll try to have a look at it this week-end.
@x1p Could you please provide us more information about your environment (server version? Mysql or MariaDB? Your DB version? Where is hosted your database? On a dedicated server, a shared host, or locally? etc..)

**Comment by x1p** [comment]
Yes, the issue still persists.
1.18.2, MariaDB, no clue, on another host
CHC v10.11.0 worked flawless

**Comment by ElBananaa** [comment]
> Yes, the issue still persists. 1.18.2, MariaDB, no clue, on another host CHC v10.11.0 worked flawless

Alright, are you on our discord? If so, can you please send me a direct message from there?
I will provide you a dev build there directly.

**Comment by UserDerezzed** [comment]
Hey, unfortunately looks like we've run into the issue again running 10.11.6.
We had tried turning off most of the chat logging, just logging anvils and books. It seemed to last for about 8 days until the cache issues began again, resulting in the "keep calm and do not restart your server" messages popping up.

Also running MariaDB, though - something important to note

**Comment by kangarko** [comment]
Hey! I am reviewing this problem again since I am home, please allow additional few days due to the 1.19 update overhead as well as other tickets so we can push this into a single update.

**Comment by ElBananaa** [comment]
@kangarko After running further investigations on my side, I found out the issue seems to be caused by the plugin writing the logs to the database. I did try a few things but they didn't work unfortunately, but I believe most changes should be done in foundation directly ^^

**Comment by kangarko** [comment]
I should have optimized this and forcefully closed database connection after the batch update. Tried and tested using MariaDb without issues, let me know if it happens again.  Apologies for the inconvenience.
