### ISSUE TITLE
Version: 1.21.4 Role wont display before name

### ISSUE THREAD

**Issue by Aideniscool123** [kangarko/ChatControl#3271]
### Are you using MySQL?

Yes

### Are you using a proxy?

No

### "/version ChatControlRed" - plugin version

11.3.6

### ZIP of "/chc debug"

[debug.zip](https://github.com/user-attachments/files/21695945/debug.zip)

### Steps to reproduce

When sending something in chat you see your message but there is no color to anything and it displays nothing before. Luck perms is being used.

**Comment by kangarko** [comment]
I don't understand your issue, can you please be more specific/send screenshot and point me exactly to what channel you are using?

**Comment by devpedrobarbosa** [comment]
@Aideniscool123 

I see you have `Cancel_Event` set to `true` in all of your channels.

Have you been able to read this [page from our docs](https://docs.mineacademy.org/chatcontrol/listener-priorities)?

Changing listener priority may solve your issue.

If it doesn't, please provide further details as @kangarko asked.

Thanks!

**Comment by Aideniscool123** [comment]
I went ahead and changed all the Cancel_Event from true to false and changed the listener priority from high-modern to lowest-modern. It does not work in any of the channels. IDK how to be more specific, all I do is type something in chat and it does not do anything besides send it. IDK if you need this but here is the debug folder again with the updated settings. 

[debug (1).zip](https://github.com/user-attachments/files/21703072/debug.1.zip)

**Comment by devpedrobarbosa** [comment]
@Aideniscool123 

Just noticed the plugin version you're using.

Please update to latest version ASAP and let us know if the problem persists.

**Comment by devpedrobarbosa** [comment]
@Aideniscool123 

Also, give it a test with freshly generated config (delete ChatControl folder and let it regenerate) and only set `Channels.Enabled` to `true`.

Thanks once again.

**Comment by Aideniscool123** [comment]
Hi, I have updated the plugin version, and used regenerated config, and I believe, unless it was the wrong thing, though I don't think so set Channels.Enabled to true. Once again here is the debug file. Thanks for your time!

[debug (2).zip](https://github.com/user-attachments/files/21706623/debug.2.zip)

**Comment by devpedrobarbosa** [comment]
@Aideniscool123 

I didn't get it. Did it work?

**Comment by Aideniscool123** [comment]
No it did not work

**Comment by kangarko** [comment]
I still dont understand exactly your issue, sorry - what should be displaying? Send screenshot of what is displaying currently.

From where does the color should come?

I looked at your configuration and lets say you go into the standard channel using /ch j standard, if you type something and previously you used /chc color menu to set a color, it will display since you have {player_chat_color}{player_chat_decoration} placeholders in the file which renders the chat channel (formats/chat.yml)

**Comment by devpedrobarbosa** [comment]
> Hi, I have updated the plugin version, and used regenerated config, and I believe, unless it was the wrong thing, though I don't think so set Channels.Enabled to true. Once again here is the debug file. Thanks for your time!
> 
> [debug (2).zip](https://github.com/user-attachments/files/21706623/debug.2.zip)

Hi there @Aideniscool123 

I downloaded your configs from this comment and tested it with latest ChatControl + latest Paper. Everything seems to be working fine.

<img width="1007" height="405" alt="Image" src="https://github.com/user-attachments/assets/07e00598-86bd-4d3b-8e83-ae0230b2303d" />

I even set up a LuckPerms prefix for me since you stated that roles are not displaying before names:

<img width="933" height="123" alt="Image" src="https://github.com/user-attachments/assets/159d114c-17f1-40ed-bff9-c77939f8894c" />

<img width="635" height="200" alt="Image" src="https://github.com/user-attachments/assets/f5028931-83bc-471a-bc5f-ee732a1c8119" />

_In **formats/chat.yml**_

I even tried setting `Cancel_Events` to true, but it also worked.

Please provide some screenshots of how it is showing on your end.

**Comment by devpedrobarbosa** [comment]
@Aideniscool123 

Do you still need support?

**Comment by Aideniscool123** [comment]
No we got it fixed thanks for your help though! Also sorry for the late reply I was very busy.

**Comment by kangarko** [comment]
Happy to hear!
